-- MuleTrace · 01 · Database, warehouse, roles and raw tables
-- Run with:  snow sql -f snowflake/01_setup.sql   (as ACCOUNTADMIN or a role with CREATE DATABASE)

CREATE WAREHOUSE IF NOT EXISTS MULETRACE_WH
  WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS MULETRACE;
CREATE SCHEMA IF NOT EXISTS MULETRACE.RAW;   -- landed source data (structured + documents)
CREATE SCHEMA IF NOT EXISTS MULETRACE.CORE;  -- features, detector output, cases
CREATE SCHEMA IF NOT EXISTS MULETRACE.APP;   -- semantic view, search service, agent

USE WAREHOUSE MULETRACE_WH;
USE SCHEMA MULETRACE.RAW;

-- Roles: investigators see masked PII; the Principal Officer sees everything and can file STRs.
CREATE ROLE IF NOT EXISTS MULETRACE_INVESTIGATOR;
CREATE ROLE IF NOT EXISTS MULETRACE_PRINCIPAL_OFFICER;
GRANT ROLE MULETRACE_INVESTIGATOR TO ROLE MULETRACE_PRINCIPAL_OFFICER;
GRANT USAGE ON WAREHOUSE MULETRACE_WH TO ROLE MULETRACE_INVESTIGATOR;
GRANT USAGE ON DATABASE MULETRACE TO ROLE MULETRACE_INVESTIGATOR;
GRANT USAGE ON ALL SCHEMAS IN DATABASE MULETRACE TO ROLE MULETRACE_INVESTIGATOR;
GRANT SELECT ON FUTURE TABLES IN DATABASE MULETRACE TO ROLE MULETRACE_INVESTIGATOR;
GRANT SELECT ON FUTURE VIEWS IN DATABASE MULETRACE TO ROLE MULETRACE_INVESTIGATOR;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE MULETRACE_INVESTIGATOR;

CREATE OR REPLACE FILE FORMAT CSV_HEADER
  TYPE = CSV PARSE_HEADER = TRUE FIELD_OPTIONALLY_ENCLOSED_BY = '"' EMPTY_FIELD_AS_NULL = TRUE;

CREATE STAGE IF NOT EXISTS LANDING FILE_FORMAT = CSV_HEADER;
CREATE STAGE IF NOT EXISTS POLICY_DOCS DIRECTORY = (ENABLE = TRUE) ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE OR REPLACE TABLE TRANSACTIONS (
  TXN_ID        STRING PRIMARY KEY,
  TIMESTAMP     TIMESTAMP_NTZ,
  FROM_ACCOUNT  STRING,
  TO_ACCOUNT    STRING,
  AMOUNT        NUMBER(14, 2),
  CHANNEL       STRING,
  LABEL         STRING COMMENT 'Ground truth in synthetic data only; never read by the detector'
);

CREATE OR REPLACE TABLE ACCOUNTS (
  ACCOUNT_ID              STRING PRIMARY KEY,
  HOLDER_NAME             STRING COMMENT 'PII — masked for non-Principal-Officer roles',
  SEGMENT                 STRING,
  ACCOUNT_TYPE            STRING,
  BRANCH                  STRING,
  OPENED_ON               DATE,
  KYC_LEVEL               STRING,
  DECLARED_MONTHLY_INCOME NUMBER(12, 2)
);
