-- MuleTrace · 02 · Load structured data and policy documents
-- Run from the repository root:  snow sql -f snowflake/02_load.sql
-- (In production these tables are fed by Openflow connectors / Snowpipe Streaming from core banking.)

USE WAREHOUSE MULETRACE_WH;
USE SCHEMA MULETRACE.RAW;

PUT file://data/transactions.csv @LANDING AUTO_COMPRESS = TRUE OVERWRITE = TRUE;
PUT file://data/accounts.csv     @LANDING AUTO_COMPRESS = TRUE OVERWRITE = TRUE;
PUT file://data/policy_chunks.csv @LANDING AUTO_COMPRESS = TRUE OVERWRITE = TRUE;
PUT file://data/policies/*.md    @POLICY_DOCS AUTO_COMPRESS = FALSE OVERWRITE = TRUE;
ALTER STAGE POLICY_DOCS REFRESH;

COPY INTO TRANSACTIONS FROM @LANDING/transactions.csv.gz
  FILE_FORMAT = (FORMAT_NAME = CSV_HEADER) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO ACCOUNTS FROM @LANDING/accounts.csv.gz
  FILE_FORMAT = (FORMAT_NAME = CSV_HEADER) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

CREATE OR REPLACE TABLE MULETRACE.CORE.POLICY_CHUNKS (
  CHUNK_ID STRING, DOC_ID STRING, DOC_TITLE STRING, SECTION STRING, HEADING STRING, CHUNK_TEXT STRING, SOURCE STRING
);
COPY INTO MULETRACE.CORE.POLICY_CHUNKS FROM @LANDING/policy_chunks.csv.gz
  FILE_FORMAT = (FORMAT_NAME = CSV_HEADER) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- Optional: for policies that arrive as PDFs / scans, parse them in Snowflake instead of pre-chunking:
-- PUT file://path/to/AML_policy.pdf @POLICY_DOCS AUTO_COMPRESS = FALSE;
-- INSERT INTO MULETRACE.CORE.POLICY_CHUNKS (CHUNK_ID, DOC_ID, DOC_TITLE, SECTION, HEADING, CHUNK_TEXT, SOURCE)
-- SELECT d.RELATIVE_PATH || '#' || c.INDEX, d.RELATIVE_PATH, d.RELATIVE_PATH, c.INDEX::STRING, NULL, c.VALUE::STRING, d.RELATIVE_PATH
-- FROM DIRECTORY(@POLICY_DOCS) d,
--      LATERAL FLATTEN(SNOWFLAKE.CORTEX.SPLIT_TEXT_RECURSIVE_CHARACTER(
--        AI_PARSE_DOCUMENT(TO_FILE('@POLICY_DOCS', d.RELATIVE_PATH), {'mode': 'LAYOUT'}):content::STRING,
--        'markdown', 1500, 200)) c
-- WHERE d.RELATIVE_PATH ILIKE '%.pdf';

SELECT 'transactions' AS t, COUNT(*) FROM TRANSACTIONS
UNION ALL SELECT 'accounts', COUNT(*) FROM ACCOUNTS
UNION ALL SELECT 'policy_chunks', COUNT(*) FROM MULETRACE.CORE.POLICY_CHUNKS;
