-- MuleTrace · 03 · Incremental flow features with Dynamic Tables
-- These keep pair-level and account-level aggregates fresh as new transactions land,
-- so the detector and the copilot query small, pre-aggregated tables instead of raw history.

USE WAREHOUSE MULETRACE_WH;
USE SCHEMA MULETRACE.CORE;

CREATE OR REPLACE DYNAMIC TABLE PAIR_FLOWS
  TARGET_LAG = '5 minutes' WAREHOUSE = MULETRACE_WH
  COMMENT = 'Money flow per sender→receiver pair'
AS
SELECT
  FROM_ACCOUNT, TO_ACCOUNT,
  COUNT(*)                              AS TXN_COUNT,
  SUM(AMOUNT)                           AS TOTAL_AMOUNT,
  COUNT_IF(AMOUNT <= 2000)              AS SMALL_TXN_COUNT,
  MODE(ROUND(AMOUNT))                   AS COMMON_AMOUNT,
  MIN(TIMESTAMP)                        AS FIRST_TS,
  MAX(TIMESTAMP)                        AS LAST_TS
FROM MULETRACE.RAW.TRANSACTIONS
GROUP BY FROM_ACCOUNT, TO_ACCOUNT;

CREATE OR REPLACE DYNAMIC TABLE ACCOUNT_FLOWS
  TARGET_LAG = '5 minutes' WAREHOUSE = MULETRACE_WH
  COMMENT = 'Inflow/outflow, counterparties and KYC context per account'
AS
WITH io AS (
  SELECT TO_ACCOUNT AS ACCOUNT_ID, AMOUNT AS IN_AMT, 0 AS OUT_AMT, FROM_ACCOUNT AS PARTY FROM MULETRACE.RAW.TRANSACTIONS
  UNION ALL
  SELECT FROM_ACCOUNT, 0, AMOUNT, TO_ACCOUNT FROM MULETRACE.RAW.TRANSACTIONS
)
SELECT
  io.ACCOUNT_ID,
  SUM(IN_AMT)                 AS IN_AMOUNT,
  SUM(OUT_AMT)                AS OUT_AMOUNT,
  COUNT_IF(IN_AMT > 0)        AS IN_COUNT,
  COUNT_IF(OUT_AMT > 0)       AS OUT_COUNT,
  COUNT(DISTINCT PARTY)       AS COUNTERPARTIES,
  ANY_VALUE(a.KYC_LEVEL)      AS KYC_LEVEL,
  ANY_VALUE(a.OPENED_ON)      AS OPENED_ON,
  ANY_VALUE(a.DECLARED_MONTHLY_INCOME) AS DECLARED_MONTHLY_INCOME,
  IFF(ANY_VALUE(a.DECLARED_MONTHLY_INCOME) > 0, SUM(IN_AMT) / ANY_VALUE(a.DECLARED_MONTHLY_INCOME), NULL) AS INFLOW_TO_INCOME
FROM io
LEFT JOIN MULETRACE.RAW.ACCOUNTS a ON a.ACCOUNT_ID = io.ACCOUNT_ID
GROUP BY io.ACCOUNT_ID;

-- Quick structuring screen straight from SQL (the Snowpark detector does the full graph analysis):
CREATE OR REPLACE VIEW STRUCTURING_SCREEN AS
SELECT TO_ACCOUNT AS COLLECTOR,
       COUNT(DISTINCT FROM_ACCOUNT) AS SENDERS,
       SUM(SMALL_TXN_COUNT)         AS SMALL_TRANSFERS,
       SUM(TOTAL_AMOUNT)            AS TOTAL_AMOUNT
FROM PAIR_FLOWS
WHERE SMALL_TXN_COUNT >= 5 AND SMALL_TXN_COUNT = TXN_COUNT
GROUP BY TO_ACCOUNT
HAVING COUNT(DISTINCT FROM_ACCOUNT) >= 10 AND SUM(TOTAL_AMOUNT) > 100000;
