-- MuleTrace · 08 · Governance: PII masking by role, hidden ground truth, least privilege
-- Investigators work on masked names; only the Principal Officer sees full identities (AML-04 §9.3).
-- Works on every Snowflake edition (secure views). On Enterprise, the masking-policy block at the end applies the
-- same rule directly on the base table.

USE WAREHOUSE MULETRACE_WH;
USE SCHEMA MULETRACE.APP;

-- Role-aware view of account master data: names masked unless the session holds the Principal Officer role.
CREATE OR REPLACE SECURE VIEW ACCOUNTS_GOVERNED
  COMMENT = 'Account master data with holder names masked for everyone except the Principal Officer'
AS
SELECT
  ACCOUNT_ID,
  CASE WHEN IS_ROLE_IN_SESSION('MULETRACE_PRINCIPAL_OFFICER') THEN HOLDER_NAME
       ELSE REGEXP_REPLACE(HOLDER_NAME, '(\\w)\\w+', '\\1•••') END AS HOLDER_NAME,
  SEGMENT, ACCOUNT_TYPE, BRANCH, OPENED_ON, KYC_LEVEL, DECLARED_MONTHLY_INCOME
FROM MULETRACE.RAW.ACCOUNTS;

-- Transactions without the synthetic ground-truth label (which must never reach investigators or the copilot).
CREATE OR REPLACE SECURE VIEW TRANSACTIONS_GOVERNED
  COMMENT = 'Transactions for investigators; excludes the synthetic LABEL column'
AS
SELECT TXN_ID, TIMESTAMP, FROM_ACCOUNT, TO_ACCOUNT, AMOUNT, CHANNEL FROM MULETRACE.RAW.TRANSACTIONS;

-- Investigators read governed views and detector output, never RAW.
REVOKE SELECT ON FUTURE TABLES IN DATABASE MULETRACE FROM ROLE MULETRACE_INVESTIGATOR;
GRANT SELECT ON VIEW ACCOUNTS_GOVERNED TO ROLE MULETRACE_INVESTIGATOR;
GRANT SELECT ON VIEW TRANSACTIONS_GOVERNED TO ROLE MULETRACE_INVESTIGATOR;
GRANT SELECT ON ALL TABLES IN SCHEMA MULETRACE.CORE TO ROLE MULETRACE_INVESTIGATOR;
GRANT SELECT ON ALL VIEWS IN SCHEMA MULETRACE.CORE TO ROLE MULETRACE_INVESTIGATOR;
GRANT INSERT ON TABLE MULETRACE.CORE.CASES TO ROLE MULETRACE_INVESTIGATOR;

-- Only the Principal Officer may write STR drafts / filings.
GRANT INSERT, UPDATE ON TABLE MULETRACE.CORE.STR_DRAFTS TO ROLE MULETRACE_PRINCIPAL_OFFICER;
GRANT USAGE ON PROCEDURE MULETRACE.CORE.DRAFT_STR(STRING, STRING) TO ROLE MULETRACE_PRINCIPAL_OFFICER;

-- Verify: as an investigator, names come back masked.
-- USE ROLE MULETRACE_INVESTIGATOR;  SELECT ACCOUNT_ID, HOLDER_NAME FROM MULETRACE.APP.ACCOUNTS_GOVERNED LIMIT 5;

-- Enterprise edition and above: enforce the same rule on the base table, tag the PII, and audit access.
-- CREATE OR REPLACE MASKING POLICY MULETRACE.CORE.MASK_HOLDER_NAME AS (val STRING) RETURNS STRING ->
--   CASE WHEN IS_ROLE_IN_SESSION('MULETRACE_PRINCIPAL_OFFICER') THEN val ELSE REGEXP_REPLACE(val, '(\\w)\\w+', '\\1•••') END;
-- ALTER TABLE MULETRACE.RAW.ACCOUNTS MODIFY COLUMN HOLDER_NAME SET MASKING POLICY MULETRACE.CORE.MASK_HOLDER_NAME;
-- CREATE TAG MULETRACE.CORE.PII_TYPE; ALTER TABLE MULETRACE.RAW.ACCOUNTS MODIFY COLUMN HOLDER_NAME SET TAG MULETRACE.CORE.PII_TYPE = 'NAME';
-- SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY WHERE ARRAY_TO_STRING(BASE_OBJECTS_ACCESSED, ',') ILIKE '%RAW.ACCOUNTS%';
