-- MuleTrace · 08 · Governance: PII masking, audit trail, least privilege
-- Investigators work on masked names; only the Principal Officer sees full identities (AML-04 §9.3).

USE WAREHOUSE MULETRACE_WH;
USE SCHEMA MULETRACE.CORE;

CREATE OR REPLACE MASKING POLICY MASK_HOLDER_NAME AS (val STRING) RETURNS STRING ->
  CASE
    WHEN IS_ROLE_IN_SESSION('MULETRACE_PRINCIPAL_OFFICER') OR IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN val
    ELSE REGEXP_REPLACE(val, '(\\w)\\w+', '\\1•••')
  END
  COMMENT = 'Masks account-holder names for everyone except the Principal Officer';

ALTER TABLE MULETRACE.RAW.ACCOUNTS MODIFY COLUMN HOLDER_NAME SET MASKING POLICY MASK_HOLDER_NAME;

CREATE TAG IF NOT EXISTS PII_TYPE ALLOWED_VALUES 'NAME', 'ACCOUNT_NUMBER';
ALTER TABLE MULETRACE.RAW.ACCOUNTS MODIFY COLUMN HOLDER_NAME SET TAG PII_TYPE = 'NAME';

-- The synthetic ground-truth label must never reach the copilot or investigators.
CREATE OR REPLACE MASKING POLICY HIDE_LABEL AS (val STRING) RETURNS STRING ->
  CASE WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN val ELSE NULL END;
ALTER TABLE MULETRACE.RAW.TRANSACTIONS MODIFY COLUMN LABEL SET MASKING POLICY HIDE_LABEL;

-- Only the Principal Officer may write STR filings.
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA MULETRACE.CORE TO ROLE MULETRACE_PRINCIPAL_OFFICER;

-- Audit: who looked at which suspicious account, and when (ACCOUNT_USAGE lags by up to ~3 hours).
CREATE OR REPLACE VIEW MULETRACE.APP.PII_ACCESS_AUDIT AS
SELECT ah.QUERY_START_TIME, ah.USER_NAME, obj.value:"objectName"::STRING AS OBJECT_NAME
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY ah,
     LATERAL FLATTEN(ah.BASE_OBJECTS_ACCESSED) obj
WHERE obj.value:"objectName"::STRING ILIKE 'MULETRACE.RAW.ACCOUNTS';

-- Verify: run as an investigator and the names come back masked.
-- USE ROLE MULETRACE_INVESTIGATOR;  SELECT ACCOUNT_ID, HOLDER_NAME FROM MULETRACE.RAW.ACCOUNTS LIMIT 5;
